#!/bin/bash
# Script de debug para verificar dados do merchant

echo "🔍 DEBUG: Verificando dados do merchant 0f6ac19c-1bc2-43f8-a289-d0cf39615f02"
echo "=================================================================="
echo ""

MERCHANT_ID="0f6ac19c-1bc2-43f8-a289-d0cf39615f02"
START_DATE="2026-04-01"
END_DATE="2026-04-30"

echo "📊 1. Verificando total de registros para este merchant:"
echo "SELECT COUNT(*) FROM ops.settlement_entry WHERE merchant_id = '$MERCHANT_ID';"
echo ""

echo "📊 2. Verificando registros no período:"
echo "SELECT COUNT(*) FROM ops.settlement_entry"
echo "WHERE merchant_id = '$MERCHANT_ID'"
echo "AND expected_settlement_date >= '$START_DATE'::date"
echo "AND expected_settlement_date <= '$END_DATE'::date;"
echo ""

echo "📊 3. Verificando distribuição por data:"
echo "SELECT"
echo "    CAST(expected_settlement_date AS DATE) as date,"
echo "    COUNT(*) as transactions,"
echo "    SUM(amount) as total_gross,"
echo "    SUM(net_amount) as total_net"
echo "FROM ops.settlement_entry"
echo "WHERE merchant_id = '$MERCHANT_ID'"
echo "AND expected_settlement_date >= '$START_DATE'::date"
echo "AND expected_settlement_date <= '$END_DATE'::date"
echo "GROUP BY CAST(expected_settlement_date AS DATE)"
echo "ORDER BY date;"
echo ""

echo "📊 4. Verificando status dos registros:"
echo "SELECT status, COUNT(*) as count"
echo "FROM ops.settlement_entry"
echo "WHERE merchant_id = '$MERCHANT_ID'"
echo "AND expected_settlement_date >= '$START_DATE'::date"
echo "AND expected_settlement_date <= '$END_DATE'::date"
echo "GROUP BY status;"
echo ""

echo "🚀 5. Testando API com merchantId como parâmetro:"
echo "curl -X GET \"http://localhost:8080/api/v1/settlements/schedule?merchantId=$MERCHANT_ID&startDate=$START_DATE&endDate=$END_DATE\" \\"
echo "  -H \"Authorization: Bearer [SEU_TOKEN]\""
echo ""

echo "💡 DICAS DE DEBUG:"
echo "=================="
echo ""
echo "1. Se COUNT = 0: Não há dados para este merchant"
echo "2. Se há dados mas API retorna 0: Problema na query SQL"
echo "3. Se API funciona com merchantId param mas não sem: Problema no token JWT"
echo "4. Verificar se as datas estão no formato correto"
echo ""

echo "🔧 SCRIPTS DE VERIFICAÇÃO:"
echo "==========================="
echo ""
echo "-- Verificar se tabela existe e tem dados"
echo "SELECT schemaname, tablename, n_live_tup as rows"
echo "FROM pg_stat_user_tables"
echo "WHERE schemaname = 'ops' AND tablename = 'settlement_entry';"
echo ""
echo "-- Verificar merchants únicos"
echo "SELECT merchant_id, COUNT(*) as records"
echo "FROM ops.settlement_entry"
echo "GROUP BY merchant_id"
echo "ORDER BY records DESC"
echo "LIMIT 5;"
