server:
  port: 8080 # Voltando para porta padrão HTTP enquanto não tem keystore
  ssl:
    enabled: false # Desabilitado até gerar o keystore.p12
    key-store: classpath:keystore.p12
    key-store-password: password 
    key-store-type: PKCS12
    key-alias: orionpay
  http2:
    enabled: true 

spring:
  application:
    name: merchant-service
  
  # Configuração explícita do Redis
  data:
    redis:
      host: 127.0.0.1
      port: 6379

  # Configuração do Spring Session
  session:
    store-type: redis
    timeout: 30m # Tempo de vida da sessão

  mail:
    host: smtp.gmail.com
    port: 587
    username: bitwisebytes@gmail.com
    password: clda bfty kpbs nieo
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
        debug: true

  datasource:
    url: jdbc:postgresql://localhost:5432/orion_payments?currentSchema=core,ops,sales,accounting,audit
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        default_schema: core
        jdbc:
          batch_size: 20
          order_inserts: false
          order_updates: false

  output:
    ansi:
      enabled: always

logging:
  config: classpath:logback-spring.xml